CLASS_MAPPING_TO_FRENCH = {
    "Apple___Apple_scab": {"culture": "Pommier", "maladie": "Tavelure"},
    "Apple___Black_rot": {"culture": "Pommier", "maladie": "Black rot"},
    "Apple___Cedar_apple_rust": {"culture": "Pommier", "maladie": "Rouille"},
    "Apple___healthy": {"culture": "Pommier", "maladie": "Sain"},
    "Background_without_leaves": {"culture": "Aucune", "maladie": "Aucune"},
    "Blueberry___healthy": {"culture": "Myrtillier", "maladie": "Sain"},
    "Cherry___Powdery_mildew": {"culture": "Cerisier", "maladie": "Oïdium"},
    "Cherry___healthy": {"culture": "Cerisier", "maladie": "Sain"},
    "Corn___Cercospora_leaf_spot Gray_leaf_spot": {"culture": "Maïs", "maladie": "Cercosporiose"},
    "Corn___Common_rust": {"culture": "Maïs", "maladie": "Rouille"},
    "Corn___Northern_Leaf_Blight": {"culture": "Maïs", "maladie": "Helminthosporiose"},
    "Corn___healthy": {"culture": "Maïs", "maladie": "Sain"},
    "Grape___Black_rot": {"culture": "Vigne", "maladie": "Black rot"},
    "Grape___Esca_(Black_Measles)": {"culture": "Vigne", "maladie": "Esca"},
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": {"culture": "Vigne", "maladie": "Tache foliaire"},
    "Grape___healthy": {"culture": "Vigne", "maladie": "Sain"},
    "Orange___Haunglongbing_(Citrus_greening)": {"culture": "Agrumes", "maladie": "Greening"},
    "Peach___Bacterial_spot": {"culture": "Pêcher", "maladie": "Bactériose"},
    "Peach___healthy": {"culture": "Pêcher", "maladie": "Sain"},
    "Pepper,_bell___Bacterial_spot": {"culture": "Poivron", "maladie": "Bactériose"},
    "Pepper,_bell___healthy": {"culture": "Poivron", "maladie": "Sain"},
    "Potato___Early_blight": {"culture": "Pomme de terre", "maladie": "Alternariose"},
    "Potato___Late_blight": {"culture": "Pomme de terre", "maladie": "Mildiou"},
    "Potato___healthy": {"culture": "Pomme de terre", "maladie": "Sain"},
    "Raspberry___healthy": {"culture": "Framboisier", "maladie": "Sain"},
    "Soybean___healthy": {"culture": "Soja", "maladie": "Sain"},
    "Squash___Powdery_mildew": {"culture": "Courgette", "maladie": "Oïdium"},
    "Strawberry___Leaf_scorch": {"culture": "Fraisier", "maladie": "Tache foliaire"},
    "Strawberry___healthy": {"culture": "Fraisier", "maladie": "Sain"},
    "Tomato___Bacterial_spot": {"culture": "Tomate", "maladie": "Bactériose"},
    "Tomato___Early_blight": {"culture": "Tomate", "maladie": "Alternariose"},
    "Tomato___Late_blight": {"culture": "Tomate", "maladie": "Mildiou"},
    "Tomato___Leaf_Mold": {"culture": "Tomate", "maladie": "Cladosporiose"},
    "Tomato___Septoria_leaf_spot": {"culture": "Tomate", "maladie": "Septoriose"},
    "Tomato___Spider_mites Two-spotted_spider_mite": {"culture": "Tomate", "maladie": "Acariens"},
    "Tomato___Target_Spot": {"culture": "Tomate", "maladie": "Corynespora"},
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {"culture": "Tomate", "maladie": "TYLCV"},
    "Tomato___Tomato_mosaic_virus": {"culture": "Tomate", "maladie": "Mosaïque"},
    "Tomato___healthy": {"culture": "Tomate", "maladie": "Sain"}
}
